#!/bin/sh
#
# download the upstream piqi tarball based on the release version given as the
# first argument
#
# usage: ./download-upstream-tarball <version> [<commit>]


VERSION="$1"
COMMIT="$2"
test -z "$VERSION" && echo "usage: $0 <version> [<commit>]" 1>&2 && exit 1

set -e
TMP=tmp.tar.gz


# NOTE: the downloaded tarball has the directory named as
# alavrik-piqi-<shortcommit> or piqi-<commit> depending on which URL was used;
# for Debian packaging to work, we need to rename the directory to
# "piqi-<version>" and repack it

if [ -z "$COMMIT" ]
then
    curl -L -o $TMP "https://api.github.com/repos/alavrik/piqi/tarball/v$VERSION"
else
    curl -L -o $TMP "https://github.com/alavrik/piqi/archive/$COMMIT/piqi-$VERSION.tar.gz"
fi

DIR="piqi-$VERSION"
rm -rf $DIR && mkdir $DIR
tar -xzf tmp.tar.gz -C $DIR --strip-components=1

tar -czf $DIR.tar.gz $DIR
rm -rf tmp.tar.gz $DIR


# ex: et sw=4 ts=4
