Document: piqi
Title: Debian piqi Manual
Author: <insert document author here>
Abstract: This manual describes what piqi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piqi/piqi.sgml.gz

Format: postscript
Files: /usr/share/doc/piqi/piqi.ps.gz

Format: text
Files: /usr/share/doc/piqi/piqi.text.gz

Format: HTML
Index: /usr/share/doc/piqi/html/index.html
Files: /usr/share/doc/piqi/html/*.html
